apiVersion: v1
data:
  API_PORT: "8080"
  CRAWLER_BASE_URL: http://crawler-service.crawler.svc.cluster.local:80
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"API_PORT":"8080"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"synergychat-api-configmap","namespace":"default"}}
  name: synergychat-api-configmap
  namespace: default
