apiVersion: v1
data:
  CRAWLER_DB_PATH: /cache/db
  CRAWLER_KEYWORDS: love,hate,joy,sadness,anger,disgust,fear,surprise
  CRAWLER_PORT: "8080"
  CRAWLER_PORT_2: "8081"
  CRAWLER_PORT_3: "8082"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"CRAWLER_KEYWORDS":"love,hate,joy,sadness,anger,disgust,fear,surprise","CRAWLER_PORT":"8080"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"synergychat-crawler-configmap","namespace":"default"}}
  creationTimestamp: "2026-09-08T19:45:45Z"
  name: synergychat-crawler-configmap
  namespace: default
  resourceVersion: "153453"
  uid: f489f57b-eb27-4521-a327-e4468f180a50
